steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', gcr.io/$PROJECT_ID/spinnaker-demo', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', 't', gcr.io/$PROJECT_ID/spnnaker-demo', 'go', 'test']
images: ['gcr.io/$PROJECT_ID/spinnaker-demo']
