gcs:
  enabled: true
  bucket: venkat-spinnaker-bucket
  project: neat-vent-281306
  jsonKey: '{
  "type": "service_account",
  "project_id": "neat-vent-281306",
  "private_key_id": "b215792b5f938c387aed4e15b0ad542ce0c3c828",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDgsPcoEu1Uw4us\nW8HfEYdW8qU/0Rg3KNdUZV56PLMie9AEK/nqISQerZxboHzwPxWFMuI0yF0pz3bP\nqYuSB6UU1xYf9l3hdb7AzA2XtGLn7hutVYjaIuoIOmQN+ow4GuUB0MyFbLBgBdqu\n9WYUc6We4+zpmnxc3j1gCZy/QtMO7dkQu2nvcDt0LiZj9rtUN2ueHfCWjPmdsT2o\nO7xZ4qTch0ZV7LTJ0vceMDhkvZIZXVgTsYXyzOFrik4t3vDh7INhspNl70KQWnTG\n2beKRUHOxfdmB3hmprNooCDwNl9s/ImmQXmSUiUDK2LU491s0YYX1agRn3C9Da9w\nNO7wiCTnAgMBAAECggEADTnaSpV9B+MwBETG1cxQpNZJBa3xGKocRrj/nzIvsmtx\nIRW8ZiluPvbZADtWfC1sC5ILs6/jOZqFmikXCjdnlbr1b/GbsOSyUxbDBBEkgBXj\nGWH/P/JHLi9o6iCIT9mLBzJuhe1FOPNcEU/O1iX0JuhJ7uER/St0MTeC1QiB2o9N\n7f19bQIQ8xbDFdWBlOVpu4wDWjSdLE5XxDqdbIxON6CD8lbmQJZtMTorEmGioMxv\npuEdLyBhowZg28EdKkggow0VPscHgws1fexOCLwXflC3QYiynKjKV9nWdWYON1P7\n0eX9KB/sR9Ite5MrtZynEgYUzdMaClUttRygDr+zAQKBgQD8xHzulKZGyq1robWK\n3jt9tkAa/PAI+u19BQ67ssvtADItytGjbLcbZZp9vrY+SA475zJlWAwJPxnfEI4m\nh+6mdsDk3Lku38GZfJvWPlorsk48evoBXMTXRVxWN4bC4whJ1WrKqzd24hQrB3wd\ncbNMUoNZjpk+gtZjXnjRfd3VAQKBgQDjkI+qpLqF45gksNeWndPVDLT++YowFrIm\nF3YFvrl4Z4I6xngSsRiwBNYGsCXusCu60k7TZc5q6rHOoc6F3hOfFY2R9P8BOuQ/\nKS5VpqNvTLRpkCyw+yZnX4qlCGCxup3RXAQ5FAnYF8h188+0g9Lk4jYpRsFFAwkn\nYQimpNfx5wKBgQDmgHg9SSlonSMQZ+MZxBcUSMKk2cw7JDi2LYqF+EKm2erof3A1\nS8qfHUSJLwUaPrNcRTVb3bL8K6L4HCzFTmh/PQQisHXfHQV7ZnrmIO4xsuRNmwep\nfmOyu/m8Vd56knbYfdpo/0IRE5G4u5afczRCgWxumu98ZewDqf8ba2CEAQKBgQDU\nn5O8y2GEDB1x2tH05s6wd8j9m8ckG3Ck6rLZt1SwTXZ+2EYEoPgCLuKTKS6oEG8r\nhaklGDB/8X3lJYZDyjXnJEo8n/9L9OyinyWt3Z9DNRY0tAMt8dv2JmzyuhsutMEU\nhrdjZXe1MrOYkg/2CF2agko80uFuS+HXq3Bb1BX47QKBgQCEWelLWn6zrxOVesJx\nfMJqiR/bzU/0sdEHQuNkrd19VvSyJN/NZPi7Ih9xfW1OMzKAARnnYPK0qi6adip3\nDNfUImToIx12OhjUSJaWsIvSut3xpRQtpD913CI9A0AWp5JHeUuVX6IA5Oilc341\ncuUV5+fN102mPqX7fTgDva3lLg==\n-----END PRIVATE KEY-----\n",
  "client_email": "spinnaker-account@neat-vent-281306.iam.gserviceaccount.com",
  "client_id": "111330889207835881097",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/spinnaker-account%40neat-vent-281306.iam.gserviceaccount.com"
}'

dockerRegistries:
- name: gcr
  address: https://gcr.io
  username: _json_key
  password: '{
  "type": "service_account",
  "project_id": "neat-vent-281306",
  "private_key_id": "b215792b5f938c387aed4e15b0ad542ce0c3c828",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDgsPcoEu1Uw4us\nW8HfEYdW8qU/0Rg3KNdUZV56PLMie9AEK/nqISQerZxboHzwPxWFMuI0yF0pz3bP\nqYuSB6UU1xYf9l3hdb7AzA2XtGLn7hutVYjaIuoIOmQN+ow4GuUB0MyFbLBgBdqu\n9WYUc6We4+zpmnxc3j1gCZy/QtMO7dkQu2nvcDt0LiZj9rtUN2ueHfCWjPmdsT2o\nO7xZ4qTch0ZV7LTJ0vceMDhkvZIZXVgTsYXyzOFrik4t3vDh7INhspNl70KQWnTG\n2beKRUHOxfdmB3hmprNooCDwNl9s/ImmQXmSUiUDK2LU491s0YYX1agRn3C9Da9w\nNO7wiCTnAgMBAAECggEADTnaSpV9B+MwBETG1cxQpNZJBa3xGKocRrj/nzIvsmtx\nIRW8ZiluPvbZADtWfC1sC5ILs6/jOZqFmikXCjdnlbr1b/GbsOSyUxbDBBEkgBXj\nGWH/P/JHLi9o6iCIT9mLBzJuhe1FOPNcEU/O1iX0JuhJ7uER/St0MTeC1QiB2o9N\n7f19bQIQ8xbDFdWBlOVpu4wDWjSdLE5XxDqdbIxON6CD8lbmQJZtMTorEmGioMxv\npuEdLyBhowZg28EdKkggow0VPscHgws1fexOCLwXflC3QYiynKjKV9nWdWYON1P7\n0eX9KB/sR9Ite5MrtZynEgYUzdMaClUttRygDr+zAQKBgQD8xHzulKZGyq1robWK\n3jt9tkAa/PAI+u19BQ67ssvtADItytGjbLcbZZp9vrY+SA475zJlWAwJPxnfEI4m\nh+6mdsDk3Lku38GZfJvWPlorsk48evoBXMTXRVxWN4bC4whJ1WrKqzd24hQrB3wd\ncbNMUoNZjpk+gtZjXnjRfd3VAQKBgQDjkI+qpLqF45gksNeWndPVDLT++YowFrIm\nF3YFvrl4Z4I6xngSsRiwBNYGsCXusCu60k7TZc5q6rHOoc6F3hOfFY2R9P8BOuQ/\nKS5VpqNvTLRpkCyw+yZnX4qlCGCxup3RXAQ5FAnYF8h188+0g9Lk4jYpRsFFAwkn\nYQimpNfx5wKBgQDmgHg9SSlonSMQZ+MZxBcUSMKk2cw7JDi2LYqF+EKm2erof3A1\nS8qfHUSJLwUaPrNcRTVb3bL8K6L4HCzFTmh/PQQisHXfHQV7ZnrmIO4xsuRNmwep\nfmOyu/m8Vd56knbYfdpo/0IRE5G4u5afczRCgWxumu98ZewDqf8ba2CEAQKBgQDU\nn5O8y2GEDB1x2tH05s6wd8j9m8ckG3Ck6rLZt1SwTXZ+2EYEoPgCLuKTKS6oEG8r\nhaklGDB/8X3lJYZDyjXnJEo8n/9L9OyinyWt3Z9DNRY0tAMt8dv2JmzyuhsutMEU\nhrdjZXe1MrOYkg/2CF2agko80uFuS+HXq3Bb1BX47QKBgQCEWelLWn6zrxOVesJx\nfMJqiR/bzU/0sdEHQuNkrd19VvSyJN/NZPi7Ih9xfW1OMzKAARnnYPK0qi6adip3\nDNfUImToIx12OhjUSJaWsIvSut3xpRQtpD913CI9A0AWp5JHeUuVX6IA5Oilc341\ncuUV5+fN102mPqX7fTgDva3lLg==\n-----END PRIVATE KEY-----\n",
  "client_email": "spinnaker-account@neat-vent-281306.iam.gserviceaccount.com",
  "client_id": "111330889207835881097",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/spinnaker-account%40neat-vent-281306.iam.gserviceaccount.com"
}'
  email: injarapu.venkat@gmail.com

# Disable minio as the default storage backend
minio:
  enabled: false

# Configure Spinnaker to enable GCP services
halyard:
  spinnakerVersion: 1.19.4
  image:
    repository: us-docker.pkg.dev/spinnaker-community/docker/halyard
    tag: 1.32.0
    pullSecrets: []
  additionalScripts:
    create: true
    data:
      enable_gcs_artifacts.sh: |-
        $HAL_COMMAND config artifact gcs account add gcs-neat-vent-281306 --json-path /opt/gcs/key.json
        $HAL_COMMAND config artifact gcs enable
      enable_pubsub_triggers.sh: |-
        $HAL_COMMAND config pubsub google enable
        $HAL_COMMAND config pubsub google subscription add gcr-triggers           --subscription-name gcr-triggers           --json-path /opt/gcs/key.json           --project neat-vent-281306           --message-format GCR
