kind: Deployment
apiVersion: apps/v1
metadata:
  name: flask-app
  labels:
   app: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: nginx
        image: gcr.io/neat-vent-281306/spinnaker-demo
        ports:
        - containerPort: 8080
      


